language: node_js
node_js:
  - node
cache:
  apt: true
  directories:
  - node_modules
script:
  - npm install
  - npm run nyc
after_success:
  # - './node_modules/.bin/nyc report --reporter=text-lcov | coveralls'
  # - npm run coveralls
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls